---
- name: Deploying maven app container
  hosts: webservergrp
  become: yes
  tasks: 

    - name: Check if Docker is already installed
      command: docker --version
      register: docker_check
      ignore_errors: yes

    - name: Download Docker install script (if not installed)
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'
      when: docker_check.rc != 0

    - name: Run Docker install script (if not installed)
      command: sh /tmp/get-docker.sh
      when: docker_check.rc != 0



        #- name: Remove conflicting Ubuntu containerd (if installed)
        #apt:
        #name: containerd
        #state: absent
        #ignore_errors: yes


    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
   
    - name: Pull Docker image
      docker_image:
        name: subashn77/mavenapp
        tag: 16
        source: pull

    - name: Run Docker container
      docker_container:
        name: maven_container
        image: subashn77/mavenapp:16
        state: started
        restart_policy: always
        ports:
          - "8080:8080"

